### ISSUE TITLE
find com.ikimuhendis:ldrawer:1.0.

### ISSUE THREAD

**Issue by ownwell** [keklikhasan/LDrawer#1]
Error:Gradle: A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find com.ikimuhendis:ldrawer:1.0.
>      Required by:
>          test:app:unspecified

**Comment by keklikhasan** [comment]
i wrote wrong version number on readme sorry. it shoul be 0.1. and fied readme.xt

**Comment by ownwell** [comment]
Thinks
