### ISSUE TITLE
Menü Animasyonu

### ISSUE THREAD

**Issue by muhammedcobanoglu** [keklikhasan/LDrawer#10]
Merhabalar,

Android'in native navigation drawer'ını kullanıyorum. DrawerArrowDrawable.java'yı projeme ekledim. "You can use like using normal drawer, instead of using" kısmını uyguladım. 
mDrawerToggle.setAnimateEnabled(true); olarak ekledim. Animasyon çalışmıyor? Eksik bir şey mi yapıyorum?

**Comment by salimkayabasi** [comment]
Bu projenin gelistirilmesi durdurulmustur. Bunun yerine Google'un hazirladigi support kutuphanelerini kullanabilirsiniz

Using support library is quite basic solution. Sorry about that but this project is deprecated.
