### ISSUE TITLE
Getting null pointer exception

### ISSUE THREAD

**Issue by taimur97** [keklikhasan/LDrawer#12]
I am using getSupportActionBar() method in my ActionBarActivity and getting the following error. Is there anything I can do to make it work?. If I change the code in the library from getActionBar() to getSupportActionBar() will it solve my problem?

E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943): java.lang.NullPointerException: expected receiver of type android.app.ActionBar, but got null
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at java.lang.reflect.Method.invokeNative(Native Method)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at java.lang.reflect.Method.invoke(Method.java:515)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.setActionBarUpIndicator(ActionBarDrawerToggle.java:130)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:57)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at com.filemanager.android.FazoolClass.onPostCreate(FazoolClass.java:171)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1150)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2167)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at android.os.Handler.dispatchMessage(Handler.java:102)
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle( 1943):     at android.os.Looper.loop(Looper.java:136)

**Comment by salimkayabasi** [comment]
Using support library is quite basic solution. Sorry about that but this project is deprecated.
