### ISSUE TITLE
getActionBar() causes NullPointerException

### ISSUE THREAD

**Issue by chenenyu** [keklikhasan/LDrawer#13]
I can't get actionBar when i use <style name="AppTheme" parent="Theme.AppCompat.Light">, but there is nothing when i use Theme.Holo.Light.DarkActionBar...

**Comment by SyedWasiHaider** [comment]
I had the same issue. Try using getSupportActionBar instead.

**Comment by salimkayabasi** [comment]
Using support library is quite basic solution. Sorry about that but this project is deprecated.
