### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'.

### ISSUE THREAD

**Issue by idemax** [keklikhasan/LDrawer#14]
Hi,

When I add the this dependence to my project I get a Manifest compatibility problem, what should I do to solve it?

The compiler tells me to user tools:overrideLibrary="com.ikimuhendis.ldrawer" to solve it. It's recommended?

Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 14 declared in library /Users/idemax/Development/Workspaces/NGTProjects/nnotes/APP/v2/app/build/intermediates/exploded-aar/com.ikimuhendis/ldrawer/0.1/AndroidManifest.xml
>     Suggestion: use tools:overrideLibrary="com.ikimuhendis.ldrawer" to force usage

**Comment by idemax** [comment]
Worked for me:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:tools="http://schemas.android.com/tools"
      package="my.app.package">

<uses-sdk tools:overrideLibrary="com.ikimuhendis.ldrawer"/>
```

**Comment by rakeshghasadiya** [comment]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 1 cannot be smaller than version 7 declared in library C:\Users\Paras\AndroidStudioProjects\MyApplication2\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="android.support.v7.appcompat" to force usage

**Comment by salimkayabasi** [comment]
Using support library is quite basic solution. Sorry about that but this project is deprecated.

**Comment by lidongming0431** [comment]
perfect
