### ISSUE TITLE
setHomeAsUpIndicator  报错误

### ISSUE THREAD

**Issue by dnydoney** [keklikhasan/LDrawer#19]
代码运行时，出现 java.lang.NoSuchMethodException: setHomeAsUpIndicator [class android.graphics.drawable.Drawable]  错误  ，请我这是什么原因啊

**Comment by baoxituo1** [comment]
Wow!The DrawerLayout requires that element to have a android:layout_gravity set on it, so I should set the gravity at RelativeLayout.

android:layout_gravity="start"

**Comment by baoxituo1** [comment]
Wow!The DrawerLayout requires that element to have a android:layout_gravity set on it, so I should set the gravity at RelativeLayout.

android:layout_gravity="start"

**Comment by baoxituo1** [comment]
Wow!The DrawerLayout requires that element to have a android:layout_gravity set on it, so I should set the gravity at RelativeLayout.

android:layout_gravity="start"

**Comment by baoxituo1** [comment]
Wow!The DrawerLayout requires that element to have a android:layout_gravity set on it, so I should set the gravity at RelativeLayout.

android:layout_gravity="start"

**Comment by Naruto469** [comment]
这个是因为setHomeAsUpIndicator 方法是API18添加的，18之前没有这个方法，所以才会报错，setHomeActionContentDescription这个方法同样也会报错的。

**Comment by waylife** [comment]
Is your activity inherit the AppcompatActivity or ActionBarActivity?
Those two are not supported now.

**Comment by salimkayabasi** [comment]
Using DrawerToggle from support library is quite basic solution. Sorry about that but this project is deprecated.
