### ISSUE TITLE
Is LDrawer support android.support.v7.app.ActionBarActivity ?

### ISSUE THREAD

**Issue by Samsu7609** [keklikhasan/LDrawer#20]
My Activity is  ActionBarActivity  and i change v4.ActionBarDrawerToggle to LDrawer's ActionBarDrawerToggle

but i got same error ActionBarDrawerToggle line 130 setHomeAsUpIndicator.invoke(mActivity.getActionBar(), mDrawerImage) 

getActionBar is null

so i think LDrawer seems not support v7.ActionBarActivity ?!

**Comment by krmao** [comment]
+1

**Comment by waylife** [comment]
Not yet.

**Comment by levelibeeka** [comment]
I've accidentally got it working! Just use `import android.support.v7.app.ActionBarDrawerToggle` instead of the library's custom one!
You can set the drawable by calling

``` java
drawerToggle.setHomeAsUpIndicator(new DrawerArrowDrawable(this) {
            @Override
            public boolean isLayoutRtl() {
                return false;
            }
        });
```

**Comment by CiccioCicc** [comment]
getSupportActionBar();

**Comment by salimkayabasi** [comment]
Using DrawerToggle from support library is quite basic solution. Sorry about that but this project is deprecated.
