### ISSUE TITLE
No hamburger icon when using support.v7.AppCompat theme

### ISSUE THREAD

**Issue by nasahapps** [keklikhasan/LDrawer#4]
It just shows the arrow, no hamburger icon. Using Theme.AppCompat.

**Comment by keklikhasan** [comment]
#6  i will fix issue as soon as possible

**Comment by nasahapps** [comment]
Nevermind, no need to. Google's appcompat library does what your library does, so no workarounds necessary.

**Comment by keklikhasan** [comment]
i originally took from them :D. and after 5.0 sdk i just got time to check it out.

**Comment by SyedWasiHaider** [comment]
I have the same issue. How exactly can I fix this?

**Comment by StahlTim** [comment]
Also facing the same issue. Any solutions?
